#!/usr/bin/env bash

# Setup Truffle box

{

set -e

echo "Truffle box creating ..."
if ! command -v truffle > /dev/null; then
  >&2 echo "[error] Truffle command not available"
  >&2 echo
  exit 1
fi

# project
TRUFFLEBOX_PRJNAME="${TRUFFLEBOX_PRJNAME:-trufflebox-webpack}"
TRUFFLEBOX_NAME="${TRUFFLEBOX_NAME:-webpack}"
# host
HOST_TRUFFLEBOX_PROJECTS_ROOT_MOUNTED=~/sf_projects
HOST_TRUFFLEBOX_PRJNAME_PATH="$HOST_TRUFFLEBOX_PROJECTS_ROOT_MOUNTED/$TRUFFLEBOX_PRJNAME"
HOST_TRUFFLEBOX_PRJNAME_APP_PATH="$HOST_TRUFFLEBOX_PROJECTS_ROOT_MOUNTED/$TRUFFLEBOX_PRJNAME/app"
HOST_TRUFFLEBOX_PRJNAME_APP_PATH_NODE_MODULES="$HOST_TRUFFLEBOX_PRJNAME_APP_PATH/node_modules"
HOST_TRUFFLEBOX_PRJNAME_LOCK_FILE="$HOST_TRUFFLEBOX_PROJECTS_ROOT_MOUNTED/.${TRUFFLEBOX_PRJNAME}.lock"
# guest
GUEST_TRUFFLEBOX_PROJECTS_ROOT=~/projects
GUEST_TRUFFLEBOX_PRJNAME_PATH="$GUEST_TRUFFLEBOX_PROJECTS_ROOT/$TRUFFLEBOX_PRJNAME"
GUEST_TRUFFLEBOX_PRJNAME_APP_PATH="$GUEST_TRUFFLEBOX_PRJNAME_PATH/app"
GUEST_TRUFFLEBOX_PRJNAME_APP_PATH_NODE_MODULES="$GUEST_TRUFFLEBOX_PRJNAME_APP_PATH/node_modules"
# tmp
TRUFFLEBOX_TMP="/tmp/${TRUFFLEBOX_PRJNAME}-tmp"

# Check lock file
if [[ -f "$HOST_TRUFFLEBOX_PRJNAME_LOCK_FILE" ]]; then
  echo "Trufflex box '$TRUFFLEBOX_PRJNAME' already created"
  exit 0
fi

# Prepare and run truffle unbox command in "temp" folder
rm -rf $TRUFFLEBOX_TMP
mkdir -p $TRUFFLEBOX_TMP
cd $TRUFFLEBOX_TMP
truffle unbox $TRUFFLEBOX_NAME

# Copy contents
# -- *NOTE* This action is destructive
rm -rf $HOST_TRUFFLEBOX_PRJNAME_PATH
mkdir -p $HOST_TRUFFLEBOX_PRJNAME_PATH
find . -type f -not -path "*node_modules*" -exec cp --parents '{}' "$HOST_TRUFFLEBOX_PRJNAME_PATH" \;

# Finalize truffle box
cd $HOST_TRUFFLEBOX_PRJNAME_APP_PATH
# -- Create shareable node_modules folder
rm -rf $GUEST_TRUFFLEBOX_PRJNAME_APP_PATH_NODE_MODULES
mkdir -p $GUEST_TRUFFLEBOX_PRJNAME_APP_PATH_NODE_MODULES
ln -sfT "$GUEST_TRUFFLEBOX_PRJNAME_APP_PATH_NODE_MODULES" "$HOST_TRUFFLEBOX_PRJNAME_APP_PATH_NODE_MODULES"

# install deps
npm install

# create lock file
touch "$HOST_TRUFFLEBOX_PRJNAME_LOCK_FILE"

exit 0
}
