# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION ||= "2"
Vagrant.require_version ">= 2.1.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = false
  end

  config.vm.define "201819_sem1_las3019" do |dhost|
    # box image
    dhost.vm.box = "ubuntu/bionic64"
    # host
    dhost.vm.hostname = "201819-sem1-las3019.test"
    # network
    dhost.vm.network "private_network", ip: "192.168.56.10"
    # virtualbox settings
    dhost.vm.provider "virtualbox" do |vb|
      vb.name = "[plas] 201819_sem1_las3019"
      vb.memory = "4096"

      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

      # gui
      vb.gui = false
      vb.customize ["modifyvm", :id, "--vram", "256"] # 256
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
      vb.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
        # cpu/core
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "85"]
      # network
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      # time sync
      vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-interval", 10000]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-min-adjust", 100]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-on-restore", 1]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000]

      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end

    # Shared folders
    dhost.vm.synced_folder "../projects", "/home/vagrant/sf_projects",
      owner: "vagrant",
      group: "vboxsf",
      mount_options: ["dmode=755"]

    # Provisioning Ethereum
    dhost.vm.provision "shell", privileged: false, inline: <<-SHELL
  sleep 5
  echo "Provision Ethereum..."
  sudo bash /vagrant/scripts/provision.sh
  echo "Fix annoying warning about 'npm update check failed'..."
  sudo chown -R $USER:$(id -gn $USER) /home/vagrant/.config
SHELL

    # Truffle box
    dhost.vm.provision "trufflebox", privileged: false, type: "shell", inline: <<-SHELL
  sleep 5
  echo "Truffle box creating..."
  TRUFFLEBOX_TMP=/tmp/trufflebox-webpack-tmp
  # Prepare and run truffle unbox command
  rm -rf $TRUFFLEBOX_TMP
  mkdir -p $TRUFFLEBOX_TMP
  cd $TRUFFLEBOX_TMP
  truffle unbox webpack
  # Create shareable node_modules folder
  sleep 5
  TRUFFLEBOX_PRJ=~/projects/trufflebox-webpack
  TRUFFLEBOX_PRJ_NM="$TRUFFLEBOX_PRJ/node_modules"
  rm -rf $TRUFFLEBOX_PRJ_NM
  mkdir -p $TRUFFLEBOX_PRJ_NM
  # Copy contents
  TRUFFLEBOX_PRJ_HOST=~/sf_projects/trufflebox-webpack
  # -- *NOTE* This action is destructive
  rm -rf $TRUFFLEBOX_PRJ_HOST
  mkdir -p $TRUFFLEBOX_PRJ_HOST
  cp -r `ls -A | grep -v "node_modules"` "$TRUFFLEBOX_PRJ_HOST/"
  cd $TRUFFLEBOX_PRJ_HOST
  ln -sfT "$TRUFFLEBOX_PRJ_NM" "$TRUFFLEBOX_PRJ_HOST/node_modules"
  npm install
SHELL
  end
end
