# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION ||= "2"
Vagrant.require_version ">= 2.1.0"

# Shared folder values
sf_smb_host = ENV["VAGRANT_SF_SMB_HOST"]
sf_smb_domain = ENV["COMPUTERNAME"]
sf_smb_username = ENV["VAGRANT_SF_SMB_USERNAME"]
sf_smb_password = ENV["VAGRANT_SF_SMB_PASSWORD"]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = false
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box

    config.cache.synced_folder_opts = {
      type: :smb,
      mount_options: ["mfsymlinks", "rw", "fsc", "dir_mode=0777,file_mode=0777"],
      group: "vboxsf",
      smb_host: sf_smb_host,
      smb_username: sf_smb_username,
      smb_password: sf_smb_password,
      smb_id: "box-ubuntu-bionic64"
    }
  end

  config.vm.define "201819_sem1_las3019" do |dhost|
    # box image
    dhost.vm.box = "ubuntu/bionic64"
    # host
    dhost.vm.hostname = "201819-sem1-las3019.test"
    # network
    dhost.vm.network "private_network", ip: "192.168.56.10"
    # virtualbox settings
    dhost.vm.provider "virtualbox" do |vb|
      vb.name = "[plas] 201819_sem1_las3019"
      vb.memory = "4096"

      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

      # gui
      vb.gui = false
      vb.customize ["modifyvm", :id, "--vram", "256"] # 256
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
      vb.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
      vb.customize ["setextradata", :id, "CustomVideoMode1", "1024x768x32"]
        # cpu/core
      vb.customize ["modifyvm", :id, "--cpus", "4"]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "85"]
      # network
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      # time sync
      vb.customize ["modifyvm", :id, "--rtcuseutc", "on"]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-interval", 10000]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-min-adjust", 100]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-on-restore", 1]
      vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 1000]

      vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
    end

    # Shared folders
    dhost.vm.synced_folder "../projects", "/home/vagrant/sf_projects",
      owner: "vagrant",
      group: "vboxsf",
      mount_options: ["dmode=755"]

    # Provisioning Ethereum
    dhost.vm.provision "shell", inline: <<-SHELL
  set -e
  echo "[info] Provision ..."
  # provision.sh
  bash /vagrant/scripts/provision.sh
SHELL

    # Set up Ethereum Development Environment
    dhost.vm.provision "devenv", type: "shell", privileged: false, inline: <<-SHELL
  set -e
  echo "[info] Set up Ethereum Development Enviroment ..."
  # setup-dev-env.sh
  bash /vagrant/scripts/setup-devenv.sh
SHELL

    # Set up Truffle box
    dhost.vm.provision "trufflebox", type: "shell", privileged: false, inline: <<-SHELL
    set -e
    echo "[info] Set up Truffle box ..."
    exec "$BASH" -il /vagrant/scripts/setup-trufflebox.sh
SHELL

  end
end
